language: java
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - wget
before_script:
- wget -q https://raw.githubusercontent.com/oehf/ipf-labs/master/maven/settings.xml --no-check-certificate
script:
- mvn deploy -q --settings settings.xml
after_script:
# Zip everything. Or use after_failure instead
- wget -q --no-check-certificate -O - https://raw.githubusercontent.com/oehf/ipf-labs/master/maven/travis_before_deploy.sh | sh
addons:
  artifacts:
    s3_region: "us-east-1"
    bucket: builds.openehealth.org
    key: AKIAIG3NJZOJH6AXNTLQ
    secret:
      secure: iAPFqtfyJAW7nAZ/jAXFH2kran0lKKULlF7fZnfnNPA8uC4QGXerEH340pdfbG4EfiRrY2MFDoEd96JNfUMB+RHuV2Zo5ueFQMFqB2FPMizM8Z2gIWds/bNbelnpiq0VMP80t4+APvu40If+80yUVitOVh+vxmKnJcy1vkYR9Cg=
    paths:
    - $(ls s3-upload/*.zip)
    target_paths: "ipf-flow-manager"
    debug: true
env:
  global:
  - secure: iTQr1okBQDnI92laZ16zu+8TYi7Igr9aP3Zzo8RIcs1bJp8mfKn5UKCUTrK93eHiGr+D705cLUl2Eve9trMhcXrovPHzeAyFb/c7np8nyVvxeMKHLKa50hsojihw0Ucx+78aMrOEvfhsH4yWa2EG6dr58rhHKyFNNkeJpZ4FeAvR5bmiaL2vqS0CSjpAjxkTwbSS6gLp+/IyHgWboYLkWsYBKMtsCtYmUkisl2hUKWFUMtwrvKaN9nkSLYjA8WluDOnTvI0srIBN0FsMNiQzNd89p88RJiBY8MOYqBTl8gqbMkzdXkRk5om7nr8Y3ZYk8tQxKfa+nv7YhMv/Y8Rucw4do1LU5cc66WFgSnmG1BqySXRmSrOzFtsHHET/O9InkQaKNmhHa+FF0914UEfXbJvfceS7Kwynn/rACrd1pBkWbFKDTcAuKOpqqw1LIVDGFlla/X7ChbAT+Zjk2CUH1pOU/DBEEruy0JKavl6p3U6Oq25mo/y+z6aXICNSggX8RboNukwISgPq/u44btJpQnvbNgkSNgzr9+Q+JuMEmkskMxOhRaXgMMRf7476Q8j3qHqkiq1V25tEA1SJEMp0hRabcDSd2yjqMuDgH/9HcmfW0pE3krHDGsvR+nRlFj3tgBNRH0VyQATt184jgevDEg/q/t+nTHTFCq+T7GL3RHk=
  - secure: U8jNMp9NpoyjClKa/cvoiQuVQz1iqjYvmW2F/1NdSRdot4tgZr0Qorausf+0lue5rPWunqcglvWOxVuKLo8gR99VdWmKJGyT46Uty43ZsO2Z5depCiYRIdxpXvcBy8OskJzNW9LvuZapyHvV/ho8WI0LElCt/oH1sGG9dAMh2VQB6bOA5Cecy/OogugzLK/RX++OTihOodJmmS8mYX7RfbNlx5laNEyAOM9mvv1BKaQKtN/e5+Nkgex//snhdOSR+p0TR5yA3R4R8aX/YF7DNeNGU/CkTbYdSW4JMVhEsPBrLl6ZRpAvmn7SuDPh5CX3hwjSWB1fgiaMSPyVr49g+hyzVpCsAjkGvX0H/0yymtVdrPliRrlzlB/rTmhKWw/FiNlOufHCGFP3dumi1tlvxRPLHmex9X93a3xzK7PTkSrhzuFhUCBs2vigmUWNx5e4YcjxC3lEFE7VA4KFMQDpzonGsMM0jHAzZtVqArjz1EQG4iQb/gbXVjEVNBWZWBb9ycuuBFMR46A+4oZrkN5U9Unk1mkUfNXIKE16iows0Tr3O+UCJRr+nJl3z1IjJslYKctbKsaJ0mBrleupkxy3Xo2Zo+iYIcPkCPjNUzRGVcASAh0hw/kyLW7+7qUzOH2+71uepOX3mZKzwhgw7wFUafhUu5LJW7r/tJ+WwRWEIVo=

