language: java
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - wget
before_script:
- wget -q https://raw.githubusercontent.com/oehf/ipf-labs/master/maven/settings.xml --no-check-certificate
script:
- mvn deploy -q --settings settings.xml
after_script:
# Zip everything. Or use after_failure instead
- wget -q --no-check-certificate -O - https://raw.githubusercontent.com/oehf/ipf-labs/master/maven/travis_before_deploy.sh | sh
addons:
  artifacts:
    s3_region: "us-east-1"
    bucket: builds.openehealth.org
    key: AKIAIG3NJZOJH6AXNTLQ
    secret:
      secure: iAPFqtfyJAW7nAZ/jAXFH2kran0lKKULlF7fZnfnNPA8uC4QGXerEH340pdfbG4EfiRrY2MFDoEd96JNfUMB+RHuV2Zo5ueFQMFqB2FPMizM8Z2gIWds/bNbelnpiq0VMP80t4+APvu40If+80yUVitOVh+vxmKnJcy1vkYR9Cg=
    paths:
    - $(ls s3-upload/*.zip)
    target_paths: "ipf-flow-manager"
    debug: true
env:
  global:
  - secure: MUwmX8kvmvpQQyzWzLmFUnFR/106O27JTIXXpJZ6qGphPZFZWBJmPJYvTdHdqb2/bs5RyBTWrK34oERJcrpn65wPPgP152KbQmb+vufBys+iKotC8g8BoTqWcopyNO8KKcdB3kHaoOj4QKFyHaGHYYPRd4IVF3knXr9+4gk6IkIK/f3Re/xZTKzRM/gYd6anWoZuevwOOrn7SYQifolfF0/qdbom1HjFVrHSUrt9Kpmd36vripZ/edl0I3smmToiFSHLKNgyqZFgdMptAozm3KXRUDlRTVfS0day2UjfjQH/+NPIYLBo/nfDUk/UG8EHaLRRxBsAd9JvQJhm8+hF8suLaI2Z5kcz+cqZ9gulikGj4Ivd5NSznj6cjB0qpKB36GdSICX0QrfXLnK6qHFQjY0RGcfLVPqO0/+bHrTL8Qmxqp5JfVTK4q333/ryqYsVB9tSWvXBw3Q6iqbFRXUilZWmeECvJjATqe6R8jESDtNXNoCUU2gcNBm3XZfC51VL6v3Fqc75tTtQp9yZq9i4YfwLgMLG1HRRWFDJ8rI43HIuDpiLrsDIC9PPNl06YZBHquroMXCwdAgp2ocuCJZdCtINWZitMuaYwX6C0iEh1R1joclkzKIqGRvPGBySX8TuWZZ3WcKIHHrSk2B80Ht7BjwoTZ7rC4mwdpQi4nGtmVM=
  - secure: OiE/QLePWirYCzGlAzu+1YH92g21gH6ER+i3Wo445q6ZBuSbtGFp9kn+E2dVvL7ttT3jo3K94IgJO6CFexr2HAaOMj1jjnXXQ9UoxA13BFJ6GEDLWftjs3wzTolgLXdGxIiH9w+RlPUSjGdUPDZjOEHPNCG+HPjfHo9qN0DAh6gYvrVBk6Dzd1beNqeoCKi0TrTUHMsci6IhInFYwczMFjdmRE7F1Xt9ZLh7kRqvw4b5YvALJhXdJAX1yThBeQZWVtmuYtzBHq7ZUB1CQ1+mNceN9XtSKZ5oy++hilW+RjMMSe6TnVKrw4eWYdC2lEbZftaZW0aiGhcF0WxbqrkFJny7gEWuH9M8wAwS9E5vCN7GgE9D3XV+p1NsSuON1kitkLzfwskcA3gp0OJJuvx7YHqZngvAcTamjrTMYGfBm00jC5d28fBF4D3VvmgV5nnIY2TvgZxWN7BpFmEQPWoZhfbI8xS1vaBwjiVcWnSThRBukNuZ0j1MZ3R7Ddg8gijpzkfj827ioIpwGdYmG57/nvf5CpuwN8bC9GVyv0Jwr8adO+AduKrNI+pTn5oFHvx6HWmD2ClTgJ4fpOtlPwNG7w55i5u9e1NyuYbdn1octbtQXObFa80WAekfzo0mq9TBzxVJp2qyo/WFKmhTxPDN/AaLDSkdZFNb90JrDe2ObAQ=

