language: java
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - wget
before_script:
- wget -q https://raw.githubusercontent.com/oehf/ipf-labs/master/maven/settings.xml --no-check-certificate
script:
- mvn deploy -q --settings settings.xml
after_script:
# Zip everything. Or use after_failure instead
- wget -q --no-check-certificate -O - https://raw.githubusercontent.com/oehf/ipf-labs/master/maven/travis_before_deploy.sh | sh
addons:
  artifacts:
    s3_region: "us-east-1"
    bucket: builds.openehealth.org
    key: AKIAIG3NJZOJH6AXNTLQ
    secret:
      secure: iAPFqtfyJAW7nAZ/jAXFH2kran0lKKULlF7fZnfnNPA8uC4QGXerEH340pdfbG4EfiRrY2MFDoEd96JNfUMB+RHuV2Zo5ueFQMFqB2FPMizM8Z2gIWds/bNbelnpiq0VMP80t4+APvu40If+80yUVitOVh+vxmKnJcy1vkYR9Cg=
    paths:
    - $(ls s3-upload/*.zip)
    target_paths: "ipf-flow-manager"
    debug: true
env:
  global:
  - secure: bqUaDw6y8b/m8DksliLq4JdMmgjJKWU7QfHpFVSfKdYNMpmUBib1xpfWDDvM7dDksTTI2RRIEKcuaIGN1+te0DcxOjndvV+lWGDpOOcaE3GjHFnvHfWAcDM7hQ5OdZl4a/M1TlPQiQftf/8RADilQbgipu/aOR2kle1+J3houSA=
  - secure: hd7CXITLDxztzy8dRwXYsDRFKr2o8vQi6idcKuVrpa7faYLFlUqN7IqmWiOu6JF/iTsKfggGTqbHNjwCtwxPKZETKsqwBopAM4pV9XfWfHPGTddoIRSq1e4BVc9XyNLJb2WCwS2U9sxigmPiSieVmuvcCTwJ6plEHeVPyfRNst0=

